todosaz/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('todoes/', include('todosaz_todoes.urls')),
    path('accounts/', include('todosaz_accounts.urls')),
    path('news/', include('todosaz_news.urls')),
    path('settings/', include('todosaz_settings.urls')),
    path('api/', include('todosaz_api.urls')),
    path('', include('todosaz_contact.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todosaz_accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('delete-account', views.del_account, name='del_account'),
    path('profile/', views.user_profile, name="profile"),
    path('edit-profile/<int:pk>/', login_required(views.EditProfile.as_view()), name="edit_profile")

]

todosaz_todoes/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = "todoes"

urlpatterns = [
    path("", login_required(views.TodoList.as_view()), name="todo_list"),
    path("<int:pk>/", login_required(views.TodoDetail.as_view()), name="todo_detail"),
    path("create/", login_required(views.CreateTodo.as_view()), name="create_todo"),
    path(
        "edit/<int:pk>/",
        login_required(views.UpdateTodo.as_view()),
        name="edit_todo",
    ),
    path(
        "delete/<int:pk>/",
        login_required(views.DeleteTodo.as_view()),
        name="delete_todo",
    ),
]

todosaz_accounts/models.py
from django.db import models

# Create your models here.

todosaz_accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.shortcuts import redirect
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())

    def login_user(self, request):
        cd = self.cleaned_data
        user = authenticate(username=cd["username"], password=cd["password"])
        if user is not None:
            login(request, user)
        self.add_error("username", "عملیات ورود با شکست مواجه شد")


class RegisterForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    re_password = forms.CharField(widget=forms.PasswordInput)

    def clean_re_password(self):
        cd = self.cleaned_data
        if cd["password"] != cd["re_password"]:
            raise forms.ValidationError("رمز های عبور مطابقت ندارند")
        return cd["password"]

    def clean_username(self):
        username = self.cleaned_data.get("username")
        is_username_exists = User.objects.filter(username=username).exists()

        if is_username_exists:
            raise forms.ValidationError("نام کاربری تکراریست")

        return username

    def register_user(self):
        cd = self.cleaned_data
        User.objects.create_user(username=cd["username"], password=cd["password"])
        return redirect("/accounts/login/")


class EditProfileForm(forms.Form):
    first_name = forms.CharField(required=False, label="نام")
    last_name = forms.CharField(required=False, label="نام خانوادگی")
    email = forms.EmailField(required=False, label="ایمیل")

    def edit_profile(self, user):
        cd = self.cleaned_data

        first_name = cd["first_name"] if "first_name" in cd else user.first_name
        last_name = cd["last_name"] if "last_name" in cd else user.last_name
        email = cd["email"] if "email" in cd else user.email
        user.first_name = first_name
        user.last_name = last_name
        user.email = email
        user.save()

todosaz_accounts/views.py
from django.views.generic.edit import UpdateView
from django.shortcuts import render, redirect

from todosaz_todoes.models import Todo
from .forms import LoginForm, RegisterForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout


def login(request):
    if not request.user.is_authenticated:
        form = LoginForm(request.POST or None)
        if form.is_valid():
            form.login_user(request)
            return redirect('/')
        return render(request, "accounts/login.html", {"form": form})
    return redirect("/")


def register(request):
    if not request.user.is_authenticated:
        form = RegisterForm(request.POST or None)
        if form.is_valid():
            form.register_user()
        return render(request, "accounts/register.html", {"form": form})
    return redirect("/")


@login_required
def del_account(request):
    loggedin_user = request.user
    if not loggedin_user.is_authenticated:
        return redirect("/accounts/login/")
    User.objects.delete(loggedin_user)
    return redirect("/accounts/register/")


@login_required
def user_profile(request):
    user = request.user
    username = user.username
    first_name = user.first_name
    last_name = user.last_name
    email = user.email
    todo_count = Todo.objects.filter(user=user).count()

    context = {
        "user": user,
        "username": username,
        "first_name": first_name,
        "last_name": last_name,
        "email": email,
        "todo_count": todo_count,
    }
    return render(request, "accounts/profile.html", context)


class EditProfile(UpdateView):
    fields = ["first_name", "last_name", "email"]
    success_url = "/accounts/profile/"
    template_name = "accounts/edit_profile.html"

    def get_queryset(self):
        username = self.request.user.username
        return User.objects.filter(username=username)


@login_required
def logout_user(request):
    logout(request)
    return redirect("/accounts/login/")

todosaz_accounts/templates/accounts/edit_profile.html
{% extends 'shared/_MainLayout.html' %}
{% block title %}ویرایش {{ object }} {% endblock title %}
{% block tabs %}
<a href="{% url 'todoes:todo_list' %}">
    <li class="tab">تودو ها</li>
</a>
<a href="{% url 'accounts:profile' %}">
    <li class="tab">حساب کاربری</li>
</a>
{% endblock tabs %}

{% block bar %}
<a href="#" data-target="mobile-demo" class="center-align sidenav-trigger"><i class="fa fa-bars"></i></a>
{% endblock bar %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="input-field">{{ form.as_p }}</div>
    <div class="center-align">
        <button type="submit" class="btn waves-effect blue">ثبت تغییرات</button>
    </div>
</form>
{% endblock content %}
{% comment %} <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">ثبت ویرایش ها</button>
</form> {% endcomment %}

todosaz_accounts/templates/accounts/login.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">ورود</button>
</form>

todosaz_accounts/templates/accounts/profile.html
{% extends 'shared/_MainLayout.html' %}
{% load static %}

{% block tabs %}
<a href="{% url 'todoes:todo_list' %}">
    <li class="tab">تودو ها</li>
</a>
<a href="{% url 'accounts:profile' %}">
    <li class="tab">حساب کاربری</li>
</a>
{% endblock tabs %}

{% block bar %}
<a href="#" data-target="mobile-demo" class="center-align sidenav-trigger"><i class="fa fa-bars"></i></a>
{% endblock bar %}

{% block title %}پروفایل شما{% endblock title %}
{% block content %}
<div class="row">
    <div class="col s12 m6">
        <div class="card medium">
            <div class="card-image"
                style="display: flex; justify-content: space-evenly; align-items: center; padding: .2rem;">
                <img style="border-radius: 50%;width: 50%;" src="{% static 'img/account-picture.jpeg' %}" />
                {% if first_name and last_name %}
                <h5>{{ first_name }} {{ last_name }}</h5>
                {% else %}
                <a href="{% url 'accounts:edit_profile' user.pk %}">نام خود را کامل کنید</a>
                {% endif %}
            </div>
            <div class="card-content">
                <p>
                    برنامه نویس فول استک جنگو و ری اکت وی در سال ۱۳۸۴ چشم به جهان
                    گشود و در سال ۱۳۹۹ وارد حوزه ی برنامه نویسی شد بعد از حدود یک
                    سال برنامه نویس بک اند شد در سال دوم با یادگیری زبان ها و
                    فریمورک های فرانت تبدیل به فول استک دولوپر شد
                    برنامه نویس فول استک جنگو و ری اکت وی در سال ۱۳۸۴ چشم به جهان
                    گشود و در سال ۱۳۹۹ وارد حوزه ی برنامه نویسی شد بعد از حدود یک
                    سال برنامه نویس بک اند شد در سال دوم با یادگیری زبان ها و
                    فریمورک های فرانت تبدیل به فول استک دولوپر شد
                    برنامه نویس فول استک جنگو و ری اکت وی در سال ۱۳۸۴ چشم به جهان
                    گشود و در سال ۱۳۹۹ وارد حوزه ی برنامه نویسی شد بعد از حدود یک
                    سال برنامه نویس بک اند شد در سال دوم با یادگیری زبان ها و
                    فریمورک های فرانت تبدیل به فول استک دولوپر شد
                </p>
                <div class="mt-3"></div>
            </div>
        </div>
    </div>
    <div class="col s12 m6">
        <div class="card small" style="height: 25pc;">
            <div class="card-title" style="padding-top: .1rem;padding-right: .2rem;">
                <h5>
                    اطلاعات حساب کاربری
                </h5>
            </div>
            <div class="card-content">
                <p>
                <div class="mt-3 row">
                    <label for="username">نام کاربری</label>
                    <h6 id="username">{{ username }}</h6>
                </div>
                <div class="mt-3 row">
                    <label for="eamil">ایمیل</label>
                    <h6 id="email">{{ email }}</h6>
                </div>
                <div class="mt-3 row">
                    <label for="username">تعداد تودو ها</label>
                    {% if todo_count != 0 %}
                    <h6 id="username">{{ todo_count }}</h6>
                    {% else %}
                    <p>شما هیچ تودویی ندارید. <a href="{% url 'todoes:create_todo' %}">یکی بسازید</a></p>
                    {% endif %}
                </div>
                </p>
                <div class="mt-3"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col m3 s6">
            <a href="{% url 'accounts:edit_profile' user.pk %}">
                <button class="btn mt-3 waves-effect blue">
                    ویرایش حساب
                </button>
            </a>
        </div>
        <div class="col m3 s6">
            <a href="{% url 'accounts:del_account' %}">
                <button class="btn waves-effect red mt-3">
                    حذف حساب
                </button>
            </a>
        </div>
    </div>
</div>
{% endblock content %}

todosaz_accounts/templates/accounts/register.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">ثبت نام</button>
</form>