todosaz/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('todoes/', include('todosaz_todoes.urls')),
    path('accounts/', include('todosaz_accounts.urls')),
    path('news/', include('todosaz_news.urls')),
    path('settings/', include('todosaz_settings.urls')),
    path('api/', include('todosaz_api.urls')),
    path('', include('todosaz_contact.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todosaz_accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('delete-account', views.del_account, name='del_account'),
    path('profile/', views.user_profile, name="profile"),
    path('edit-profile/<int:pk>/', login_required(views.EditProfile.as_view()), name="edit_profile")

]

todosaz_todoes/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = "todoes"

urlpatterns = [
    path("", login_required(views.TodoList.as_view()), name="todo_list"),
    path("<int:pk>/", login_required(views.TodoDetail.as_view()), name="todo_detail"),
    path("create/", login_required(views.CreateTodo.as_view()), name="create_todo"),
    path(
        "edit/<int:pk>/",
        login_required(views.UpdateTodo.as_view()),
        name="edit_todo",
    ),
    path(
        "delete/<int:pk>/",
        login_required(views.DeleteTodo.as_view()),
        name="delete_todo",
    ),
]

todosaz_todoes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Todo(models.Model):
    title = models.CharField(verbose_name="عنوان", max_length=48)
    created = models.DateField(verbose_name="زمان ایجاد", auto_now_add=True)
    is_active = models.BooleanField(verbose_name="فعال/غیرفعال", default=True)
    text = models.TextField(verbose_name="متن")
    user = models.ForeignKey(User, verbose_name="کاربر", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "تودو"
        verbose_name_plural = "تودو ها"

    def get_absolute_url(self):
        return reverse("todoes:todo_detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title

todosaz_todoes/forms.py
from .models import Todo
from django import forms


class CreateTodoForm(forms.Form):
    title = forms.CharField(label="عنوان")
    text = forms.CharField(widget=forms.Textarea, label="متن")

    def create_todo(self, user):
        cd = self.cleaned_data
        Todo.objects.create(
            title=cd["title"], text=cd["text"], user=user
        )

todosaz_todoes/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView, FormView
from .models import Todo
from .forms import CreateTodoForm


class TodoList(ListView):
    template_name = "todoes/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context

    def get_queryset(self):
        usr = self.request.user
        return Todo.objects.filter(user=usr).order_by("-pk")


class TodoDetail(DetailView):
    model = Todo
    template_name = "todoes/detail.html"

    def get_queryset(self):
        usr = self.request.user
        return Todo.objects.filter(user=usr)


class CreateTodo(FormView):
    form_class = CreateTodoForm
    success_url = "/todoes/"
    template_name = "todoes/create.html"

    def form_valid(self, form):
        form.create_todo(user=self.request.user)
        return super().form_valid(form)


class UpdateTodo(UpdateView):
    fields = ["title", "text"]
    template_name = "todoes/update.html"
    success_url = "/todoes/"

    def get_queryset(self):
        usr = self.request.user
        return Todo.objects.filter(user=usr)


class DeleteTodo(DeleteView):
    model = Todo
    template_name = "todoes/delete.html"
    success_url = "/todoes/"

    def get_queryset(self):
        usr = self.request.user
        return Todo.objects.filter(user=usr)

todosaz_todoes/templates/todoes/create.html
{% extends 'shared/_MainLayout.html' %}
{% block title %}ساخت تودو{% endblock title %}
{% block tabs %}
<a href="{% url 'todoes:todo_list' %}">
    <li class="tab">تودو ها</li>
</a>
<a href="{% url 'accounts:profile' %}">
    <li class="tab">حساب کاربری</li>
</a>
{% endblock tabs %}

{% block bar %}
<a href="#" data-target="mobile-demo" class="center-align sidenav-trigger"><i class="fa fa-bars"></i></a>
{% endblock bar %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="input-field materialize-textarea">{{ form.as_p }}</div>
    <div class="center-align">
        <button type="submit" class="btn waves-effect blue">اضافه کردن تودو</button>
    </div>
</form>
{% endblock content %}

todosaz_todoes/templates/todoes/delete.html
{% extends 'shared/_MainLayout.html' %}
{% block title %}حذف {{ todo.title }}{% endblock title %}
{% block tabs %}
<a href="{% url 'todoes:todo_list' %}">
    <li class="tab">تودو ها</li>
</a>
<a href="{% url 'accounts:profile' %}">
    <li class="tab">حساب کاربری</li>
</a>
{% endblock tabs %}

{% block bar %}
<a href="#" data-target="mobile-demo" class="center-align sidenav-trigger"><i class="fa fa-bars"></i></a>
{% endblock bar %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h5>آیا واقعا می خواهی "{{ todo }}" را حذف کنی </h5>
    <div class="center-align mt-3">
        <button type="submit" class="btn waves-effect red">بله</button>
        <button onclick="window.history.back()" class="btn waves-effect green">
            خیر
        </button>
    </div>
</form>
{% endblock content %}

todosaz_todoes/templates/todoes/detail.html
{% extends 'shared/_MainLayout.html' %}

{% block title %} {{ todo.title }} {% endblock title %}

{% block tabs %}
<a href="{% url 'todoes:todo_list' %}">
    <li class="tab">تودو ها</li>
</a>
<a href="{% url 'accounts:profile' %}">
    <li class="tab">حساب کاربری</li>
</a>
{% endblock tabs %}

{% block bar %}
<a href="#" data-target="mobile-demo" class="center-align sidenav-trigger"><i class="fa fa-bars"></i></a>
{% endblock bar %}

{% block content %}
<div class="row">
    <div class="col s12">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ todo.title }}</span>
                <p>{{ todo.text }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'todoes:edit_todo' todo.pk %}">
                    <button class="btn btn-small waves-effect green">ویرایش</button>
                </a>
                <a href="{% url 'todoes:delete_todo' todo.pk %}">
                    <button class="btn btn-small waves-effect red">حذف</button>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

todosaz_todoes/templates/todoes/list.html
{% extends 'shared/_MainLayout.html' %}

{% block title %}لیست تودو ها{% endblock title %}

{% block tabs %}
<a href="{% url 'todoes:todo_list' %}">
    <li class="tab">تودو ها</li>
</a>
<a href="{% url 'accounts:profile' %}">
    <li class="tab">حساب کاربری</li>
</a>
{% endblock tabs %}

{% block bar %}
<a href="#" data-target="mobile-demo" class="center-align sidenav-trigger"><i class="fa fa-bars"></i></a>
{% endblock bar %}

{% block content %}
<div class="fixed-action-btn">
    <a href="{% url 'todoes:create_todo' %}" class="waves-effect btn-floating btn-large blue">
        <i class="fas fa-plus"></i>
    </a>
</div>
{% if todo_list %}
<div class="col s9">
    <ul class="collapsible todo-list">
        {% for todo in todo_list %}
        <li>
            <a href="{% url 'todoes:todo_detail' todo.pk %}">
                <div class="collapsible-header">
                    {{ todo.title }}
                </div>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% else %}
<p>شما هیچ تودویی ندارید. از طریق آیکن پایین صفحه میتوانید یکی اضافه کنید</p>
{% endif %}
{% endblock content %}

todosaz_todoes/templates/todoes/update.html
{% extends 'shared/_MainLayout.html' %}
{% block title %}ویرایش {{ object }} {% endblock title %}
{% block tabs %}
<a href="{% url 'todoes:todo_list' %}">
    <li class="tab">تودو ها</li>
</a>
<a href="{% url 'accounts:profile' %}">
    <li class="tab">حساب کاربری</li>
</a>
{% endblock tabs %}

{% block bar %}
<a href="#" data-target="mobile-demo" class="center-align sidenav-trigger"><i class="fa fa-bars"></i></a>
{% endblock bar %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="input-field">{{ form.as_p }}</div>
    <div class="center-align">
        <button type="submit" class="btn waves-effect blue">ثبت تغییرات</button>
    </div>
</form>
{% endblock content %}